apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sentinel-bot
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm/sentinel-bot
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/mexxo-dvp/sentinel-bot
      tag: develop         # або інший реальний тег, що існує в GHCR
      pullPolicy: IfNotPresent
    imagePullSecrets:      # додамо на кроці 2, якщо образ приватний
    #  - name: ghcr-cred
    teleToken:
      secretName: sentinel-bot
      secretKey: token
