apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mexxo-dvp/sentinel-bot
    targetRevision: develop
    path: helm/sentinel-bot
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
