apiVersion: v2
name: sentinel-bot
description: Helm chart for sentinel-bot
type: application
<<<<<<< HEAD
version: 1.0.0
=======
version: 1.0.2
>>>>>>> 8c5820a (helm: image='repo:tag' (no os/arch); chart 1.0.2; tag=main)
appVersion: "v1.0.0"
