replicaCount: 1

image:
  repository: ghcr.io/mexxo-dvp/sentinel-bot
  tag: main
  pullPolicy: IfNotPresent

# лишаємо порожнім за замовчуванням: у GKE задаємо через HR
imagePullSecrets: []

teleToken:
  secretName: sentinel-bot
  secretKey: token
