apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel-bot.fullname" . }}
  labels:
    {{- include "sentinel-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "sentinel-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sentinel-bot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "sentinel-bot.fullname" . }}
          image: "{{ default .Values.repository .Values.image.repository }}:{{ default .Values.tag .Values.image.tag }}{{- if or .Values.image.os .Values.os }}-{{ default .Values.os .Values.image.os }}{{- end }}{{- if or .Values.image.arch .Values.arch }}-{{ default .Values.arch .Values.image.arch }}{{- end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: TELE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.teleToken.secretName }}
                  key: {{ .Values.teleToken.secretKey }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
